mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.guoguo.knowledge.entity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/knowledge
    username: root
    password: 666666
system:
  name: 知识站